from db_connect import DbConnect

class ComprobanteModel:

    def __init__(self):
        self.conn = DbConnect().connect()

        if self.conn is None:
            raise ConnectionError("No se pudo establecer la conexi√≥n a la base de datos.")

        self.cursor = self.conn.cursor(dictionary=True)

    def create_comprobante(self, datos):
        sql = "INSERT INTO comprobantes (id_comprobante, ruta_carpeta, fecha_carga, descripcion, statu) " \
        "VALUES (%s, %s, %s, %s, %s)"
      
        try: 
            self.cursor.execute(sql, tuple(datos))
            self.conn.commit()
            return self.cursor.lastrowid

        except Exception as e:
            self.conn.rollback()
            print(f"Error inesperado: {e}")
            return None

    def update_comprobante(self, datos):
        sql = "UPDATE comprobantes SET ruta_carpeta = %s, descripcion = %s " \
        "WHERE id_comprobante = %s"
        
        try: 
            self.cursor.execute(sql, tuple(datos))
            self.conn.commit()
            return self.cursor.rowcount

        except Exception as e:
            self.conn.rollback()
            print(f"Error inesperado: {e}")
            return None

    def delete_comprobante(self, id):
        sql = "DELETE FROM comprobantes WHERE id_comprobante = %s"
        try: 
            self.cursor.execute(sql, (id))
            self.conn.commit()
            return self.cursor.rowcount

        except Exception as e:
            self.conn.rollback()
            print(f"Error inesperado: {e}")
            return None
